/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MediaGenerator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MediaQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MessageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ResponseGenerator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WhatsAppApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WhatsAppWebhook": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}